export const NAVBAR_OPEN = 'NAVBAR_OPEN';
export const NAVBAR_CLOSE = 'NAVBAR_CLOSE';
export const MODAL_LOGIN_OPEN = 'MODAL_LOGIN_OPEN';
export const MODAL_LOGIN_CLOSE = 'MODAL_LOGIN_CLOSE';
export const MODAL_SIGNUP_OPEN = 'MODAL_SIGNUP_OPEN';
export const MODAL_SIGNUP_CLOSE = 'MODAL_SIGNUP_CLOSE';
